sonar.projectKey=LuiTzY_PRUEBA-TECNICA-APAP
sonar.projectName=PRUEBA-TECNICA-APAP
sonar.projectVersion=1.0.0
sonar.organization=luitzy

#Aqui especificamos que va a utilizar
#codigo de la app
sonar.sources=src

#tests aqui
sonar.tests=test

#Aqui le pasamos el output que genera jest al hacer los reportes
sonar.javascript.lcov.reportPaths=coverage/lcov.info


#aqui excluimos los modulos de node y otros archivos
sonar.exclusions=node_modules/**,coverage/**