apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Lista de archivos que forman la base
# Kustomize los combina todos en un solo YAML
resources:
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - networkpolicy.yaml

# Agrega estos labels a TODOS los recursos automáticamente
commonLabels:
  app.kubernetes.io/name: prueba-tecnica-apap