apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Le decimos que tome todo de la base
resources:
  - ../../base

# Namespace donde se despliega en dev
namespace: dev

# La imagen que usa este ambiente
# el action de git siempre actualiza el registry con la ultima imagen, por eso usamos el latest
images:
  - name: prueba-tecnica-apap
    newName: ghcr.io/luity/prueba-tecnica
    newTag: latest

# ponemos el sufijo de dev para poder identificar los recursos asociados 
nameSuffix: "-dev"

# Parches específicos de dev
patches:
  - path: patch-replicas.yaml