
#PIPELINE que sera ejecutado en push de branch de develop o en pull req de master, main

name: CI/CD Prueba tecnica de APAP
on:
  push: 
    branches: [main]
  pull_request: 
    branches: [main,master,develop]

#declaramos variables globales
env:
  REGISTRY: ghcr.io 
  IMAGE_NAME: ${{github.repository}} 


#Trabajos a ejecutar, primero CI, luego CD
jobs:

  ci:
    name: Build, Test, Scan y Push de imagen 

    #runner a utilzar
    runs-on: ubuntu-latest

    #Permisos necesarios para las acciones que va a ejecutar este job
    permissions:
      contents: read
      packages: write 

    
    #Pasos a seguir, aqui empezamos descargando codigo, seteando el ambiente etc
    steps:

      # descarga el codigo en el runner de github para tener acceso a todo el codigo de la app
      - name: Checkout de codigo fuente
        uses: actions/checkout@v6

        #parametros necesarios sobre todo para la lectura de sonaquber

        with:

          fetch-depth: 0 #esto le indica a sonar que lea todo el historial de commits


      #Validacion despues del checkout
      - name: Escaneando leaks de Secrets del repo
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Instalacion de node (Seteando ambiente)
        uses: actions/setup-node@v6

        with:
          #aqui utilizamos basicamente la misma version de la imagen de node de docker
          node-version: '25.8.1'

      #
      - name: Instalacion de deps del proyecto
        run: npm ci
  

      - name: Buscando errores con ESLint
        run: npm run lint --fix

      - name: Ejecutando test del proyecto
        run: npm test --coverage --ci
      

      - name:  Publicar artifacts generados 
        uses: actions/upload-artifact@v6
        # always() asegura que se suba incluso si las pruebas fallaron
        if: always()
        with:
          name: coverage-report
          path: coverage/
          retention-days: 7

      
      - name: Analisis con SonarCube( SonarCloud )
        uses: SonarSource/sonarcloud-github-action@master
        #Como req pide token de sonar y token de git que se setea automatico
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKENa }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


      - name: Configurando Docker Buildx para Build de imagen
        uses: docker/setup-buildx-action@v3

      - name: Login a Github Registry de imagenes
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }} 
          password: ${{ secrets.GITHUB_TOKEN }}



      - name: Extraccion de data de la imagen de docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,prefix=sha-,format=short
            type=ref,event=branch
            type=ref,event=pr
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}


      - name: Convertir image name a minusculas
        run: echo "IMAGE_NAME_LOWER=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Obtener SHA corto
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

# Construye la imagen pero NO la sube al registry todavía
      # La guarda en el cache local de Docker (load: true)
      # para que Trivy pueda escanearla en el siguiente step
      - name: Build de imagen Docker para trivy
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          load: true
          tags: local-build:latest 
          labels: ${{ steps.meta.outputs.labels }}
          # se acelera el buld utilizando cache
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name:  Escaneo de vulnerabilidades con Trivy
        uses: aquasecurity/trivy-action@master
        with:
          #path de la imagen a analizar
          image-ref: local-build:latest
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL'
          vuln-type: 'os,library'
          output: 'trivy-report.txt'

      # Obtenemos el reporte que trivy nos da
      - name: Obtener reporte de Trivy
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: trivy-report
          path: trivy-report.txt
          retention-days: 7

      # Subimos la imagen al registry
      - name: Push imagen al registry
        uses: docker/build-push-action@v5
        if: github.event_name == 'push'
        with:
          context: .
          push: true
          #Aqui extraemos la info del step de la data de docker 
          tags: ${{ steps.meta.outputs.tags }} 
          labels: ${{ steps.meta.outputs.labels }}
        

      # Guardamos el sha del commit para el job de CD
      - name: Guardar image tag como output para flujo CD
        id: image-tag
        run: echo "tag=sha-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Notificar por teams Chanel APAP Prueba tecnica
        uses: jdcargile/ms-teams-notification@v1.4

        with:
              github-token: ${{ github.token }} 
              ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
              notification-summary: Despliegue CI completado
              notification-color: 17a2b8
              timezone: America/Santo_Domingo
              verbose-logging: true


      - name: Notificar por teams Chanel APAP Prueba tecnica (Si falla)
        uses: jdcargile/ms-teams-notification@v1.4
        if: failure()
        with:
              github-token: ${{ github.token }} 
              ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
              notification-summary: Despliegue CI fallo
              notification-color: FF0000   
              timezone: America/Santo_Domingo
              verbose-logging: true
    # Expone el output para que el job CD pueda usarlo
    outputs:
      image-tag: ${{ steps.image-tag.outputs.tag }}



      

  cd:
    name:  Actualizar GitOps para ArgoCD
    runs-on: ubuntu-latest
    needs: ci #requiere que ya el CI se haya completado
    # Solo en push a develop (no en PRs)
    if: github.event_name == 'push'

    steps:

      # Aqui accedemos al codigo del mismo repo que en este caso es el que mantiene el patron de gitops
      - name: Checkout repo de GitOps
        uses: actions/checkout@v4
        with:
          #usamos un token pat
          token: ${{ secrets.GITOPS_TOKEN }}


      - name: Instalacion de Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Convertir image name a minúsculas
        run: echo "IMAGE_NAME_LOWER=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      # ── Aqui editamos el kustomize del ambiente que seleccionamos, tomamos el tag generado de la imagen
      # y seteamos la imagen con kustomize y el tag correcto dentro del registry
      # hacemos un commit
      - name: Actualizar image tag en overlay dev
        run: |
          cd k8s/overlays/prod
          kustomize edit set image prueba-tecnica-apap=${{ env.REGISTRY }}/${{ env.IMAGE_NAME_LOWER }}:${{ needs.ci.outputs.image-tag }}
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Actualizado tag de imagen ${{ needs.ci.outputs.image-tag }} [skip ci]"
          git push
      #Nota: skip ci evita que se haga un loop al hacer los commits, es decir este commit no va a lanzar el flujo de ci ya previamente hecho