
#PIPELINE que sera ejecutado en push de branch de develop o en pull req de master, main

name: CI/CD Prueba tecnica de APAP
on:
  push: 
    branches: [develop]
  pull_request: 
    branches: [main,master]

#declaramos variables globales
env:
  REGISTRY: ghcr.io 
  IMAGE_NAME: ${{github.repository}} 


#Trabajos a ejecutar, primero CI, luego CD
jobs:

  ci:
    name: Build, Test, Scan y Push de imagen 

    #runner a utilzar
    runs-on: ubuntu-last 

    #Permisos necesarios para las acciones que va a ejecutar este job
    permissions:
      contents: read
      packages: write 

    
    #Pasos a seguir, aqui empezamos descargando codigo, seteando el ambiente etc
    steps:

      # descarga el codigo en el runner de github para tener acceso a todo el codigo de la app
      - name: Checkout de codigo fuente
        uses: actions/checkout@v6

        #parametros necesarios sobre todo para la lectura de sonaquber

        with:

          fetch-depth: 0 #esto le indica a sonar que lea todo el historial de commits

      - name: Instalacion de node (Seteando ambiente)
        uses: actions/setup-node@v6

        with:
          #aqui utilizamos basicamente la misma version de la imagen de node de docker
          node-version: '25.8.1'

      #
      - name: Instalacion de deps del proyecto
        run: npm ci
  

      - name: Ejecutando test del proyecto
        run: npm test --coverage --ci
      

      - name:  Publicar artifacts generados 
        uses: actions/upload-artifact@v6
        # always() asegura que se suba incluso si las pruebas fallaron
        if: always()
        with:
          name: coverage-report
          path: coverage/
          retention-days: 7

      
      - name: Analisis con SonarCube( SonarCloud )
        uses: SonarSource/sonarcloud-github-action@master
        #Como req pide token de sonar y token de git que se setea automatico
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


      - name: Configurando Docker Buildx para Build de imagen
        uses: docker/setup-buildx-action@v3

      - name: Login a Github Registry de imagenes
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }} 
          password: ${{ secrets.GITHUB_TOKEN }}
          
  # cd: