
#PIPELINE que sera ejecutado en push de branch de develop o en pull req de master, main

name: CI/CD Prueba tecnica de APAP
on:
  push: 
    branches: [develop]

  pull_request: [main,master]

#declaramos variables globales
env:
  REGISTRY: ghcr.io 
  IMAGE_NAME: ${{github.repository}} 


#Trabajos a ejecutar, primero CI, luego CD
jobs:

  ci:
    name: Build, Test, Scan y Push de imagen 

    #runner a utilzar
    runs-on: ubuntu-last 

    #Permisos necesarios para las acciones que va a ejecutar este job
    permissions:
      contents: read
      packages: write 

    
    #Pasos a seguir, aqui empezamos descargando codigo, seteando el ambiente etc
    steps:

      # descarga el codigo en el runner de github para tener acceso a todo el codigo de la app
      - name: Checkout de codigo fuente
        uses: actions/checkout@v6

        #parametros necesarios sobre todo para la lectura de sonaquber

        with:

          fetch-depth: 0 #esto le indica a sonar que lea todo el historial de commits

      - name: Instalacion de node (Seteando ambiente)
        uses: actions/setup-node@v6

        with:
          #aqui utilizamos basicamente la misma version de la imagen de node de docker
          node-version: '25.8.1'

      #
      - name: Instalacion de deps del proyecto
        run: npm ci
  

      - name: Ejecutando test del proyecto
        run: npm test --coverage --ci
      #
  # cd: